name: Build
on: [push, workflow_dispatch]
jobs:
  build-android:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Build VGPU_VK
        run: |
         wget https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
         unzip android-ndk-r26d-linux.zip >> /dev/null
         $ANDROID_NDK_HOME/ndk-build APP_PLATFORM=android-24 APP_BUILD_SCRIPT=./Android.mk NDK_PROJECT_PATH=Application.mk.
         python glslang/update_glslang_sources.py
      - name: Upload VGPU_VK libs
        uses: actions/upload-artifact@v4
        with:
          name: vgpu_vk-android
          path: libs/*
